### ISSUE TITLE
Is BackoffStrategy intended to be a public or a private interface?

### ISSUE THREAD

**Issue by firminochangani** [nidorx/retry#1]
Hi @nidorx, how is it going?
I've found your project on `r/golang` and nice work.

A quick question, the interface [`BackoffStrategy`](https://github.com/nidorx/retry/blob/46593bf1225e018ed44452e21b4e4a51fd1c7dc9/retry.go#L9) is public but it contains a private method which makes it _uncallable_ from outside the package, is this intended?

Cheers,
Firmino

**Comment by nidorx** [comment]
Thanks @flowck . I updated the interface and it is now possible to implement custom strategies.

https://github.com/nidorx/retry/commit/9ece996e0f37b8a1d497ee5d64de98ffc8ad9c0b
